#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import lexika
import collections

# Cet objet est fait pour être modifié, mais avec quelques précautions...
class InformationsLinguistiques:
    def __init__(self):
        # Dictionnaire de données qui sera rempli à l'initialisation de la création du dictionnaire.
        self.statuts_langues = {
            "source 1": None,
            "source 2": None,
            "cible 1": None,
            "cible 2": None,
            "cible 3": None,
            "cible 4": "f",
        }

    def initialiser(self):
        self.format_entrée = {
            "MDF": {
                "créateur": "nébuleuse d'Orion",
                "modèle de ligne": r"^\\(?P<balise>\w*)\s*(?P<données>.*)",
                "modèle de renvoi automatique": r"(?P<ensemble>fv:(?P<cible>[\w_~-]+))|(?P<ensemble>\|fv{(?P<cible>[\w\s~\[\]-]+)})",
                "balises": {
                    "lx": {"entité": "vedette", "paramètres": {}, "tête": "primaire"},
                    "se": {"entité": "sous-vedette", "paramètres": {}, "tête": "secondaire"},
                    "hm": {"entité": "homonyme", "paramètres": {}},
                    "va": {"entité": "variante", "paramètres": {}},
                    "ps": {"entité": "classe grammaticale", "paramètres": {}},
                    "ph": {"entité": "phonétique", "paramètres": {}},
                    "sn": {"entité": "acception", "paramètres": {}},
                    "de": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "xe": {"entité": "traduction d'exemple", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "xv": {"entité": "exemple", "paramètres": {"langue": self.statuts_langues["source 1"]}},
                    "xn": {"entité": "traduction d'exemple", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "re": {"entité": "équivalent", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "ge": {"entité": "glose", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "gn": {"entité": "glose", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "ue": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "usage"}},
                    "nq": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "interrogation"}},
                    "nt": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "général"}},
                    "ng": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "grammaire"}},
                    "np": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "phonologie"}},
                    "cf": {"entité": "relation sémantique", "paramètres": {"type": "confer"}},
                    "bw": {"entité": "relation sémantique", "paramètres": {"type": "emprunt"}},
                    "sy": {"entité": "relation sémantique", "paramètres": {"type": "synonyme"}},
                    "an": {"entité": "relation sémantique", "paramètres": {"type": "antonyme"}},
                    "ce": {"entité": "traduction de relation sémantique", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "sd": {"entité": "domaine sémantique", "paramètres": {}},
                    "lt": {"entité": "sens littéral", "paramètres": {}},
                    "mr": {"entité": "morphologie", "paramètres": {}},
                    "sc": {"entité": "nom scientifique", "paramètres": {}},
                    "dt": {"entité": "date", "paramètres": {}},
                    "so": {"entité": "source", "paramètres": {}},
                    "lf": {"entité": "type de relation sémantique", "paramètres": {}},
                    "lv": {"entité": "relation sémantique", "paramètres": {}},
                    "le": {"entité": "traduction de relation sémantique", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "1d": {"entité": "forme duelle", "paramètres": {"langue": self.statuts_langues["source 1"]}},
                    "pl": {"entité": "forme plurielle", "paramètres": {"langue": self.statuts_langues["source 1"]}},
                    "vpl": {"entité": "variante de forme plurielle", "paramètres": {"langue": self.statuts_langues["source 1"]}},
                    "wav": {"entité": "média", "paramètres": {"type": "audio", "qualité": "élevée", "format": "wav"}},
                }
            },
            "Lexware": {
                "créateur": "nébuleuse d'Oméga",
                "modèle de ligne": r"^(?P<acception>\d*)(?P<profondeur>[.]*)(?P<balise>[\w]*)\s*(?P<données>.*)",
                "modèle de renvoi automatique": r"(?P<ensemble>\\lang{(?P<cible>[¹²³⁴\d\w\s~\(\)\/-]+)})",
                "balises": {
                    "hw": {"entité": "vedette", "paramètres": {}, "tête": "primaire"},
                    "hix": {"entité": "homonyme", "paramètres": {}},
                    "ps": {"entité": "classe grammaticale", "paramètres": {}},
                    "dff": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "dfe": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "dfn": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 4"]}},
                    "nag": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 3"]}},
                    "dfbot": {"entité": "nom scientifique", "paramètres": {}},
                    "dfi": {"entité": "équivalent", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "emp": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "usage"}},
                }
            },
            "MDF Alex": {
                "créateur": "nébuleuse d'Orion",
                "modèle de ligne": r"^\\(?P<balise>\w*)\s*(?P<données>.*)",
                "modèle de renvoi automatique": r"(?P<ensemble>fv:(?P<cible>[\w_~-]+))|(?P<ensemble>\|fv{(?P<cible>[\w\s~\[\]-]+)})",
                "balises": {
                    "lx": {"entité": "vedette", "paramètres": {}},
                    "hm": {"entité": "homonyme", "paramètres": {}},
                    "ps": {"entité": "classe grammaticale", "paramètres": {}},
                    "ph": {"entité": "phonétique", "paramètres": {}},
                    "la": {"entité": "forme de citation", "paramètres": {}},
                    "wr": {"entité": "groupe", "paramètres": {}},
                    "sn": {"entité": "acception", "paramètres": {}},
                    "se": {"entité": "sous-entrée", "paramètres": {}},
                    "de": {"entité": "définition", "paramètres": {"langue": "fra"}},
                    "dn": {"entité": "définition", "paramètres": {"langue": "eng"}},
                    "xe": {"entité": "traduction d'exemple", "paramètres": {"langue": "fra"}},
                    "xn": {"entité": "traduction d'exemple", "paramètres": {"langue": "eng"}},
                    "xv": {"entité": "exemple", "paramètres": {"langue": "mlv"}},
                    "oe": {"entité": "commentaire", "paramètres": {"langue": "fra"}},
                    "lf": {"entité": "type de relation sémantique", "paramètres": {}},
                    "lv": {"entité": "relation sémantique", "paramètres": {}},
                    "tab": {"entité": "tableau", "paramètres": {}},
                    "con": {"entité": "contenu", "paramètres": {"langue": "fra"}},
                    "tif": {"entité": "titre", "paramètres": {"langue": "fra"}},
                    "tiv": {"entité": "titre", "paramètres": {"langue": "mlv"}},
                }
            }
        }

        self.format_sortie = {
            "LMF": {
                "modèle de renvoi": r"^(?P<entrée_lexicale>[\w\s~\[\].-]+?)(?P<numéro_homonyme>[\d]*)$",
                "constantes": {"entrée lexicale": "Ⓔ", "numéro d'homonyme": "Ⓗ", "sous-entrée lexicale": "ⓔ", "sens": "Ⓢ"},
                "entités à trier": {"entrées lexicales": "identifiant"},
                "entités à extraire" : [{"parent": {"entité": "entrée lexicale", "attribut": "entrées lexicales", "nom": "entrée principale"}, "enfant": {"entité": "sous-entrée lexicale", "attribut": "sous-entrées lexicales", "nom": "sous-entrée"}}],
                "entités à lier": [{"lemmes": "lexeme"}],
                "entités": {
                    "informations globales": {"entités": {"nom": "informations globales", "attributs": {}, "paramètres": {}, "structure": {}},
                                              "parents": "/"},
                    "dictionnaire": {"entités": {"nom": "dictionnaire", "attributs": {}, "structure": {}},
                                     "parents": "/"},
                    "langue": {"entités": {"nom": "langue", "attributs": {}, "structure": {}},
                               "parents": [{"nom": "informations globales", "attribut": "langues"}]},
                    "entrée": {"entités": [{"nom": "entrée lexicale", "attributs": {},
                                            "structure": {"tête": True, "identifiant": {"nom": "identifiant", "type": "primaire"}}}],
                               "parents": [{"nom": "dictionnaire", "attribut": "entrées lexicales"}]},
                    "sous-entrée": {"entités": [{"nom": "sous-entrée lexicale", "attributs": {},
                                            "structure": {"tête": True, "identifiant": {"nom": "identifiant", "type": "primaire"}}}],
                               "parents": [{"nom": "entrée lexicale", "attribut": "sous-entrées lexicales"}]},
                    "vedette": {"entités": [{"nom": "lemme", "attributs": {"lexeme": None}, "structure": {}}],
                                "parents": [{"entité": "entrée", "attributs": {}, "informations": {"identifiant": "lexeme"}},
                                            {"nom": "entrée lexicale", "attribut": "lemmes"}]},
                    "sous-vedette": {"entités": [{"nom": "lemme", "attributs": {"lexeme": None}, "structure": {}}],
                                "parents": [{"entité": "sous-entrée", "attributs": {}, "informations": {"identifiant": "lexeme"}},
                                            {"nom": "sous-entrée lexicale", "attribut": "lemmes"}]},
                    "homonyme": {"entités": [{"nom": "entrée lexicale", "attributs": {"numéro d'homonyme": None},
                                              "structure": {"identifiant": {"nom": "numéro d'homonyme", "type": "secondaire"}}}],
                                 "parents": None},
                    "classe grammaticale": {"entités": [{"nom": "entrée lexicale", "attributs": {"partie du discours": None}, "structure": {}},
                                                        {"nom": "sous-entrée lexicale", "attributs": {"partie du discours": None}, "structure": {}}],
                                            "parents": None},
                    "variante": {"entités": [{"nom": "représentation de forme", "attributs": {"phonétique": None}, "structure": {}}],
                                 "parents": [{"nom": "lemme", "attribut": "représentations"}]},
                    "phonétique": {"entités": [{"nom": "représentation de forme", "attributs": {"phonétique": None}, "structure": {}}],
                                   "parents": [{"nom": "lemme", "attribut": "représentations"}]},
                    "acception": {"entités": [{"nom": "sens", "attributs": {"numéro de sens": None},
                                               "structure": {"identifiant": {"nom": "numéro de sens", "type": "primaire"}}}],
                                  "parents": [{"nom": "entrée lexicale", "attribut": "sens"},
                                              {"nom": "sous-entrée lexicale", "attribut": "sens"}]},
                    "glose": {"entités": [{"nom": "définition", "attributs": {"glose": None}, "structure": {}}],
                              "parents": [{"nom": "sens", "attribut": "définitions"},
                                          {"entité": "acception", "attributs": {"numéro de sens": "0"}, "informations": {}}]},
                    "définition": {"entités": [{"nom": "définition", "attributs": {"définition": None}, "structure": {}}],
                                   "parents": [{"nom": "sens", "attribut": "définitions"},
                                               {"entité": "acception", "attributs": {"numéro de sens": "0"}, "informations": {}}]},
                    "nom scientifique": {"entités": [{"nom": "déclaration", "attributs": {"nom scientifique": None}, "structure": {}}],
                                         "parents": [{"nom": "définition", "attribut": "déclarations"},
                                                     {"entité": "définition", "attributs": {}}]},
                    "sens littéral": {"entités": [{"nom": "représentation de texte", "attributs": {"sens littéral": None}, "structure": {}},
                                                  {"nom": "définition", "attributs": {"sens littéral": None}, "structure": {}},
                                                  {"nom": "traduction de relation sémantique", "attributs": {"sens littéral": None}, "structure": {}}],
                                      "parents": None},
                    "morphologie": {"entités": [{"nom": "paradigme", "attributs": {"morphologie": None}, "structure": {}}],
                                    "parents": [{"nom": "sens", "attribut": "définitions"},
                                                {"entité": "acception", "attributs": {"numéro de sens": "0"},
                                                 "informations": {}}]},
                    "exemple": {
                        "entités": [{"nom": "représentation de texte", "attributs": {"forme écrite": None}, "structure": {}}],
                        "parents": [{"entité": "contexte", "attributs": {"type": "exemple"}, "informations": {}},
                                    {"nom": "contexte", "attribut": "représentations de texte"}]},
                    "traduction d'exemple": {
                        "entités": [{"nom": "représentation de texte", "attributs": {"forme écrite": None}, "structure": {}}],
                        "parents": [{"nom": "contexte", "attribut": "représentations de texte"},
                                    {"entité": "contexte", "attributs": {"type": "exemple"}, "informations": {}}]},
                    "contexte": {"entités": [{"nom": "contexte", "attributs": {"type": None}, "structure": {}}],
                                 "parents": [{"nom": "sens", "attribut": "contextes"},
                                             {"entité": "acception", "attributs": {"numéro de sens": "0"}, "informations": {}}]},
                    "équivalent": {"entités": [{"nom": "équivalent", "attributs": {"traduction": None}, "structure": {}}],
                                   "parents": [{"nom": "sens", "attribut": "équivalents"},
                                               {"entité": "acception", "attributs": {"numéro de sens": "0"}, "informations": {}}]},
                    "note": {"entités": [{"nom": "déclaration", "attributs": {"traduction": None}, "structure": {}}],
                             "parents": [{"nom": "définition", "attribut": "déclarations"},
                                         {"entité": "définition", "attributs": {}}]},
                    "type de relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"type": None}, "structure": {}}],
                                                    "parents": [{"nom": "sens", "attribut": "équivalents"},
                                                                {"entité": "acception", "attributs": {"numéro de sens": "0"}, "informations": {}}]},
                    "relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"cible": None}, "structure": {}}],
                                            "parents": [{"nom": "sens", "attribut": "équivalents"},
                                                        {"entité": "acception", "attributs": {"numéro de sens": "0"}, "informations": {}}]},
                    "forme apparentée": {"entités": [{"nom": "forme apparentée", "attributs": {"cible": None}, "structure": {}}],
                                         "parents": [{"nom": "entrée lexicale", "attribut": "formes apparentées"}]},
                    "traduction de relation sémantique": {
                        "entités": [{"nom": "traduction de relation sémantique", "attributs": {"traduction": None}, "structure": {}}],
                        "parents": [{"nom": "relation sémantique", "attribut": "traductions"}]},
                    "domaine sémantique": {"entités": [{"nom": "champ disciplinaire", "attributs": {"domaine sémantique": None}, "structure": {}}],
                                           "parents": [{"nom": "sens", "attribut": "définitions"},
                                                       {"entité": "acception", "attributs": {"numéro de sens": "0"},
                                                        "informations": {}}]},
                    "forme duelle": {"entités": [{"nom": "représentation de forme", "attributs": {"forme écrite": None}, "structure": {}}],
                                        "parents": [{"entité": "forme de mot", "attributs": {"nombre grammatical": "duel"}, "informations": {}},
                                                    {"nom": "forme de mot", "attribut": "représentations de forme"}]},
                    "forme plurielle": {"entités": [{"nom": "représentation de forme", "attributs": {"forme écrite": None}, "structure": {}}],
                                        "parents": [{"entité": "forme de mot", "attributs": {"nombre grammatical": "pluriel"}, "informations": {}},
                                                    {"nom": "forme de mot", "attribut": "représentations de forme"}]},
                    "variante de forme plurielle": {"entités": [{"nom": "représentation de forme", "attributs": {"variante": None}, "structure": {}}],
                                                    "parents": [{"nom": "forme de mot", "attribut": "variantes"},
                                                                {"entité": "forme de mot", "attributs": {"nombre grammatical": "pluriel"}, "informations": {}}]},
                    "forme de mot": {"entités": [{"nom": "forme de mot", "attributs": {}, "structure": {}}],
                                     "parents": [{"nom": "entrée lexicale", "attribut": "formes de mot"}]},
                    "date": {"entités": [{"nom": "entrée lexicale", "attributs": {"date": None}, "structure": {}}],
                             "parents": None},
                    "source": {"entités": [{"nom": "entrée lexicale", "attributs": {"source": None}, "structure": {}},],
                               "parents": None},
                    "média": {"entités": [{"nom": "média", "attributs": {"chemin": None}, "structure": {}}],
                              "parents": [{"nom": "entrée lexicale", "attribut": "médias"}]},
                }
            },
            "Alex": {
                "modèle de renvoi": r"^(?P<entrée>[\w\s~\[\].-]+?)(?P<homonyme>[\d]*)(?P<groupe>[A-Z]*)$",
                "entités à trier": {"entrées": "identifiant"},
                "entités": {
                    "vedette": {"entités": [{"nom": "entrée", "attributs": {"vedette": None},
                                             "structure": {"tête": True, "identifiant": {"nom": "vedette", "type": "primaire"}}}],
                                "parents": [{"nom": "dictionnaire", "attribut": "entrées"}]},
                    "homonyme": {"entités": [{"nom": "entrée", "attributs": {"homonyme": None},
                                              "structure": {"identifiant": {"nom": "homonyme", "type": "secondaire"}}}],
                                 "parents": None},
                    "classe grammaticale": {
                        "entités": [{"nom": "sous-entrée", "attributs": {"classe grammaticale": None}, "structure": {}},
                                    {"nom": "groupe", "attributs": {"classe grammaticale": None}, "structure": {}},
                                    {"nom": "entrée", "attributs": {"classe grammaticale": None}, "structure": {}}],
                        "parents": None},
                    "phonétique": {"entités": [{"nom": "entrée", "attributs": {"phonétique": None}, "structure": {}}],
                                   "parents": None},
                    "forme de citation": {
                        "entités": [{"nom": "entrée", "attributs": {"forme de citation": None}, "structure": {}}],
                        "parents": None},
                    "groupe": {"entités": [{"nom": "groupe", "attributs": {"nom": None},
                                            "structure": {"identifiant": {"nom": "nom", "type": "primaire"}}}],
                               "parents": [{"nom": "entrée", "attribut": "groupes"}]},
                    "acception": {"entités": [{"nom": "sens", "attributs": {"acception": None},
                                               "structure": {"identifiant": {"nom": "acception", "type": "primaire"}}}],
                                  "parents": [{"nom": "groupe", "attribut": "groupes"}, {"nom": "entrée", "attribut": "sens"}]},
                    "sous-entrée": {"entités": [{"nom": "sous-entrée", "attributs": {"vedette": None},
                                                 "structure": {"identifiant": {"nom": "vedette", "type": "primaire"}}}],
                                    "parents": [{"nom": "sens", "attribut": "sous-entrées"},
                                                {"nom": "entrée", "attribut": "sous-entrées"}]},
                    "définition": {"entités": [{"nom": "définition", "attributs": {"définition": None},
                                                "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                   "parents": [{"nom": "sous-entrée", "attribut": "définitions"},
                                               {"nom": "sens", "attribut": "définitions"},
                                               {"nom": "groupe", "attribut": "groupes"},
                                               {"nom": "entrée", "attribut": "définitions"}]},
                    "exemple": {"entités": [{"nom": "exemple", "attributs": {"exemple": None},
                                             "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                "parents": [{"nom": "sous-entrée", "attribut": "exemples"},
                                            {"nom": "sens", "attribut": "exemples"},
                                            {"nom": "entrée", "attribut": "exemples"}]},
                    "traduction d'exemple": {"entités": [{"nom": "traduction d'exemple", "attributs": {"traduction": None},
                                                          "structure": {}}],
                                             "parents": [{"nom": "exemple", "attribut": "traductions"}]},
                    "commentaire": {"entités": [{"nom": "note", "attributs": {"commentaire": None}, "structure": {}}],
                                    "parents": [{"nom": "exemple", "attribut": "notes"}]},
                    "type de relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"type": None}, "structure": {}}],
                                                    "parents": [{"nom": "entrée", "attribut": "relations sémantiques"},
                                                                {"nom": "sous-entrée", "attribut": "relations sémantiques"},
                                                                {"nom": "sens", "attribut": "relations sémantiques"}]},
                    "relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"cible": None}, "structure": {"factorisable": True}},
                                                        {"entité": "type de relation sémantique", "attributs": {}, "copie": {"type": "type"}}],
                                            "parents": None},
                    "tableau": {"entités": [{"nom": "tableau", "attributs": {"identifiant": None},
                                             "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                "parents": [{"nom": "sous-entrée", "attribut": "tableaux"},
                                            {"nom": "sens", "attribut": "tableaux"},
                                            {"nom": "entrée", "attribut": "tableaux"}]},
                    "contenu": {"entités": [{"nom": "tableau", "attributs": {"contenu": None}, "structure": {}}],
                                "parents": None},
                    "titre": {"entités": [{"nom": "titre", "attributs": {"titre": None}, "structure": {}}],
                              "parents": [{"nom": "tableau", "attribut": "titres"}]},
                }
            },
        }

        self.créateurs = {
            "nébuleuse d'Orion": lambda configuration: lexika.NébuleuseDʼOrion(configuration),
            "nébuleuse d'Oméga": lambda configuration: lexika.NébuleuseDʼOméga(configuration),
        }
