chemin source: exemples/mwotlap.lex
chemin cible: mwotlap.xml
format entrée: MDF Alex
format sortie: Alex
sens: direct
type: normal
hiérarchie: normale
identifiant: mwotlap - test
dictionnaire:
  nom: Essai d'un dictionnaire mwotlap
  auteur: Alexandre François
  commentaire: "dictionnaire très élaboré : cas très difficile (groupes, sous-entrées, sous-sens, etc.)"
XML:
  format: structure totale
  langue: fra
  XSL: style.xsl
ordre lexicographique: [a, b, c, d, e, ē, g, h, i, k, l, m, m, n, ̄n, o, ō, p, q, r, s, t, u, v, w, y]
tri: normal
langues:
- identifiant: mlv
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: mwotlap
  glossonyme: mwotlap
  statut: source
- identifiant: fra
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: français
  glossonyme: français
  statut: cible
- identifiant: eng
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: English
  glossonyme: anglais
  statut: cible
créateur: nébuleuse obscure
tâches:
  initial:
  - remplacer caractères
  - joindre lignes coupées
  prémédian:
  postmédian:
  final:
  - créer liens automatiques
