chemin source: exemples/tamaŋ.txt
chemin cible: tamaŋ.xml
format entrée: Martine
format sortie: structure totale
sens: direct
type: normal
hiérarchie: normale
identifiant: tamaŋ - test
dictionnaire:
  nom: Essai d'un dictionnaire tamaŋ
  auteur: Martine Mazaudon
  commentaire: Test avec la nouvelle bibiliothèque
XML:
  XSL: style.xsl
ordre lexicographique:
tri: inverse
langues:
- identifiant: tam
  type caractères: nagari
  sens lecture: gauche à droite
  autoglossonyme: tamaŋ
  glossonyme: tamaŋ
  statuts: [source, vernaculaire]
- identifiant: fra
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: français
  glossonyme: français
  statuts: [cible]
- identifiant: eng
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: English
  glossonyme: anglais
  statuts: [cible]
- identifiant: nep
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: nepali
  glossonyme: népali
  statuts: [source, vernaculaire]
créateur: nébuleuse obscure
tâches:
  initial:
  prémédian:
  postmédian:
  final:
  - créer liens automatiques