chemin source: exemples/Mwotlap_BIG.lex
chemin cible: mwotlap.xml
type source: Alex
sens: direct
type: normal
hiérarchie: normale
identifiant: mwotlap - test
dictionnaire:
  nom: Essai d'un dictionnaire mwotlap
  auteur: Alexandre François
  commentaire: "dictionnaire très élaboré : cas très difficile (groupes, sous-entrées, sous-sens, etc.)"
langues:
- identifiant: mlv
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: mwotlap
  glossonyme: mwotlap
  statuts: [source, vernaculaire]
- identifiant: fra
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: français
  glossonyme: français
  statuts: [cible]
- identifiant: eng
  type caractères: latin
  sens lecture: gauche à droite
  autoglossonyme: English
  glossonyme: anglais
  statuts: [cible]
créateur: nébuleuse obscure
tâches:
- joindre lignes coupées
