configuration:
  chemin source: informations linguistiques.yml
base:
  chemin source: japhug.lex
  format d’entrée: MDF Guillaume
  format de sortie: LMF Guillaume
  identifiant: japhug
général:
  nom: 嘉绒-汉-法词典
  auteur: Guillaume Jacques
  commentaire: Test LMF-α
  ordre lexicographique: 
      - [a, ɤ, b, β, c, ɕ, d, e, f, g, ɣ, ɢ, h, i, j, ɟ, k, l, ɬ, m, n, ɲ, ŋ, ɴ, o, p, q, r, ʁ, s, ʂ, t, ɯ, w, x, χ, z, ʑ, ʐ]
langues:
- code: jya
  type de caractères: latin
  glossonyme: japhug
  statut: source
- code: fra
  type de caractères: latin
  glossonyme: français
  statut: cible
- code: cmn
  type de caractères: hanzi
  autoglossonyme: 普通话
  glossonyme: chinois
  statut: cible
xml:
  chemin cible: japhug.xml
  format: α #αβγ
  langue: fra
  XSL: style.xsl
  tri: normal
latex:
  format: standard
  chemin du gabarit: latex.xsl
  langue: fra
  chemin cible: résultats/japhug.tex
  fichiers annexes:
    introduction: introduction.tex


