configuration:
  chemin source: exemples/japhug/informations linguistiques.yml
base:
  chemin source: exemples/japhug/japhug.lex
  format d’entrée: MDF Guillaume
  format de sortie: LMF Guillaume
  identifiant: japhug
général:
  nom: 嘉绒-汉-法词典
  auteur: Guillaume Jacques
  commentaire: Test LMF-α
  ordre lexicographique: 
      - [a, ɤ, b, β, c, ɕ, d, e, f, g, ɣ, ɢ, h, i, j, ɟ, k, l, ɬ, m, n, ɲ, ŋ, ɴ, o, p, q, r, ʁ, s, ʂ, t, ɯ, w, x, χ, z, ʑ, ʐ]
langues:
  jya:
      type de caractères: latin
      autoglossonyme: japhug
      glossonyme: japhug
      statut: source
  fra:
      type de caractères: latin
      autoglossonyme: français
      glossonyme: français
      statut: cible
  cmn:
      type de caractères: hanzi
      autoglossonyme: 普通话
      glossonyme: chinois
      statut: cible
XML:
  chemin cible: exemples/japhug/japhug.xml
  format: α #αβγ
  langue: fra
  XSL: style.xsl
  tri: normal
Latex:
  format: standard
  gabarit: exemples/japhug/latex.xsl
  langue: fra
  chemin cible: exemples/japhug/résultats/japhug.tex
  fichiers annexes:
    introduction: exemples/japhug/introduction.tex


