configuration:
  chemin source: exemples/yuanga/informations linguistiques.yml
base:
  chemin source: exemples/yuanga/yuanga.lex
  format d’entrée: MDF Isabelle
  format de sortie: LMF Isabelle
  identifiant: yuanga
général:
  nom: Essai d’un dictionnaire
  auteur: Isabelle Bril
  commentaire: LMF-α
  ordre lexicographique: 
    - [[a, ã], b, bw, c, ç, ch, d, dr, [e, è, ẽ, ê], f, fh, g, h, [i, î], j, k, kh, l, lh, m, mh, ń, n, ńh, nh, [o, ò, õ, ô], p, ph, r, rh, s, sh, t, tr, th, thr, [u, û], v, vh, vw, w, wh, x, y, yh, z, zh]
langues:
  nua:
      type de caractères: latin
      autoglossonyme: yuanga-zuanga
      glossonyme: yuanga-zuanga
      statut: source
  fra:
      type de caractères: latin
      autoglossonyme: français
      glossonyme: français
      statut: cible
  eng:
      type de caractères: latin
      autoglossonyme: English
      glossonyme: anglais
      statut: cible
XML:
  chemin cible: exemples/yuanga/yuanga.xml
  format: α #αβγ
  langue: fra
  XSL: style.xsl
  tri: normal

