#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import lexika
import collections
from lexika.configuration.informations_linguistiques import InformationsLinguistiques
from pprint import pprint


class InformationsLinguistiquesPersonnalisées(InformationsLinguistiques):
    def __init__(self, statuts_langues):
        super(InformationsLinguistiquesPersonnalisées, self).__init__(statuts_langues)

        self.formats_entrée = {
            "MDF Alex": {
                "créateur": "nébuleuse d'Orion",
                "modèle de ligne": r"^\\(?P<balise>\w*)\s*(?P<données>.*)",
                "modèle de renvoi automatique": r"(?P<ensemble>(?:fv|vl):(?P<cible>[\w\~'–_-]+))|(?P<ensemble>\|(?:fv|vl){(?P<cible>[\w\s\[\]\~'–_-]+)})|<(?:phraseme|variante)>(?P<ensemble>(?P<cible>[\w\s~\[\]-–]+))<\/(?:phraseme|variante)>",
                "modèle de style": r"(?P<ensemble>(?P<style>{0}):(?P<texte>[\w,.;:!?/\[\]\(\){{}}\~‘’'–_*+-]+))|(?P<ensemble>\|(?P<style>{0}){{(?P<texte>[\w\s\[\],.;:!?/\[\]\(\){{}}\~‘’'–_*+-]+)}})".format("|".join(["fl", "ax", "fv", "vl", "fr", "fe", "fs", "fi", "hm"])),
                "balises": dict(self.formats_entrée["MDF"]["balises"], **{
                    "se": {"entité": "sous-vedette", "paramètres": {}},
                    "la": {"entité": "forme de citation", "paramètres": {}},
                    "he": {"entité": "étiquette sémantique", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "hn": {"entité": "étiquette sémantique", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "lt": {"entité": "sens littéral", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "ll": {"entité": "sens littéral", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "we": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "syntaxique"}},
                    "wn": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 2"], "type": "syntaxique"}},
                    "wr": {"entité": "groupe", "paramètres": {}},
                    "tab": {"entité": "tableau", "paramètres": {}},
                    "enc": {"entité": "encadré", "paramètres": {}},
                    "tiv": {"entité": "titre", "paramètres": {"langue": self.statuts_langues["source 1"]}},
                    "tie": {"entité": "titre", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "tin": {"entité": "titre", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "con": {"entité": "contenu", "paramètres": {}},
                    "conv": {"entité": "contenu", "paramètres": {"langue": self.statuts_langues["source 1"]}},
                    "conf": {"entité": "contenu", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "cona": {"entité": "contenu", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "dc": {"entité": "date", "paramètres": {"type": "création"}},
                    "dt": {"entité": "date", "paramètres": {"type": "modification"}},
                    "pc": None,
                    "img": {"entité": "image", "paramètres": {}},
                    "lg": {"entité": "légende d'image", "paramètres": {}},
                    "oe": {"entité": "commentaire d'exemple", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "on": {"entité": "commentaire d'exemple", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "ur": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "usage"}},
                    "uv": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 2"], "type": "usage"}},
                })
            },
            "MDF Guillaume": dict(self.formats_entrée["MDF"], **{
                "balises": dict(self.formats_entrée["MDF"]["balises"], **{
                    "wav": {"entité": "média", "paramètres": {"type": "audio", "qualité": "élevée", "format": "wav"}},
                    "wav8": {"entité": "média", "paramètres": {"type": "audio", "qualité": "faible", "format": "wav"}},
                })
            }),
            "MDF Alexis": {
                "créateur": "nébuleuse d'Orion",
                "modèle de ligne": r"^^\\(?P<balise>\w*)\s*(?P<métadonnées><([\w\s]+=[\w\"\s]+)+>)?\s*(?P<données>.*)",
                "modèle de style": r"(?P<ensemble>(?P<style>{0}):(?P<texte>[\w˥˧˩#$/\[\]\(\){{}}\~‘’'–_*+.-]+))|(?P<ensemble>\|(?P<style>{0}){{(?P<texte>[\w\s˥˧˩#$\[\]/\[\]\(\){{}}\~‘’'–_*+.-]+)}})".format(
                    "|".join(["fl", "fn", "fv", "vl", "fr", "fe", "fs", "fi", "fg", "hm"])),
                "balises": dict(self.formats_entrée["MDF"]["balises"], **{
                    "ton": {"entité": "ton", "paramètres": {}},
                    "df": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "de": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "dn": {"entité": "définition", "paramètres": {"langue": self.statuts_langues["cible 3"]}},
                    "gf": {"entité": "glose", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "ge": {"entité": "glose", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "gn": {"entité": "glose", "paramètres": {"langue": self.statuts_langues["cible 3"]}},
                    "xf": {"entité": "traduction d'exemple", "paramètres": {"langue": self.statuts_langues["cible 1"]}},
                    "xe": {"entité": "traduction d'exemple", "paramètres": {"langue": self.statuts_langues["cible 2"]}},
                    "xn": {"entité": "traduction d'exemple", "paramètres": {"langue": self.statuts_langues["cible 3"]}},
                    "sf": {"entité": "référence", "paramètres": {}},
                    "vf": {"entité": "note", "paramètres": {"langue": self.statuts_langues["cible 1"], "type": "variante"}},
                })
            }
        }

        self.formats_sortie = {
            "personnalisé Alex": {
                "modèle de renvoi": r"^(?P<entrée>[\w\s~\[\].-]+?)(?P<homonyme>[\d]*)(?P<groupe>[A-Z]*)$",
                "constantes": {"entrée": "Ⓔ", "sous-entrée": "Ⓝ", "homonyme": "Ⓗ", "groupe": "Ⓖ", "sens": "Ⓢ", "définition": "ⓓ", "glose": "ⓖ", "exemple": "⒠", "tableau": "ⓣ", "encadré": "ⓝ"},
                "entités à trier": {"entrées": "identifiant"},
                "entités à extraire": [{"parent": {"entité": "entrée lexicale", "attribut": "entrées lexicales", "nom": "entrée principale"}, "enfant": {"entité": "sous-entrée lexicale", "attribut": "sous-entrées lexicales", "nom": "sous-entrée"}}],
                "entités à lier": [{"entrée": "vedette"}, {"entrée": "forme de citation"}],
                "entités": {
                    "vedette": {"entités": [{"nom": "entrée", "attributs": {"vedette": None},
                                             "structure": {"tête": True, "identifiant": {"nom": "vedette", "type": "primaire"}}}],
                                "parents": [{"nom": "dictionnaire", "attribut": "entrées"}]},
                    "homonyme": {"entités": [{"nom": "entrée", "attributs": {"homonyme": None},
                                              "structure": {"identifiant": {"nom": "homonyme", "type": "secondaire"}}}],
                                 "parents": None},
                    "classe grammaticale": {
                        "entités": [{"nom": "sous-entrée", "attributs": {"classe grammaticale": None}, "structure": {}},
                                    {"nom": "groupe", "attributs": {"classe grammaticale": None}, "structure": {}},
                                    {"nom": "entrée", "attributs": {"classe grammaticale": None}, "structure": {}}],
                        "parents": None},
                    "phonétique": {"entités": [{"nom": "entrée", "attributs": {"phonétique": None}, "structure": {}}],
                                   "parents": None},
                    "forme de citation": {
                        "entités": [{"nom": "entrée", "attributs": {"forme de citation": None}, "structure": {}},
                                    {"nom": "sous-entrée", "attributs": {"forme de citation": None}, "structure": {}}],
                        "parents": None},
                    "reduplication": {
                        "entités": [{"nom": "entrée", "attributs": {"reduplication": None}, "structure": {}}],
                        "parents": None},
                    "variante": {"entités": [{"nom": "variante", "attributs": {"variante": None}, "structure": {}}],
                                         "parents": [{"nom": "sous-entrée", "attribut": "variantes"},
                                                     {"nom": "sens", "attribut": "variantes"},
                                                     {"nom": "groupe", "attribut": "variantes"},
                                                     {"nom": "entrée", "attribut": "variantes"}]},
                    "paradigme": {"entités": [{"nom": "paradigme", "attributs": {"forme": None},
                                                "structure": {}}],
                                   "parents": [{"nom": "sous-entrée", "attribut": "paradigmes"},
                                               {"nom": "sens", "attribut": "paradigmes"},
                                               {"nom": "groupe", "attribut": "paradigmes"},
                                               {"nom": "entrée", "attribut": "paradigmes"}]},
                    "morphologie": {"entités": [{"nom": "entrée", "attributs": {"morphologie": None}, "structure": {}}],
                                    "parents": None},
                    "groupe": {"entités": [{"nom": "groupe", "attributs": {"nom": None},
                                            "structure": {"identifiant": {"nom": "nom", "type": "primaire"}}}],
                               "parents": [{"nom": "entrée", "attribut": "groupes"}]},
                    "acception": {"entités": [{"nom": "sens", "attributs": {"acception": None},
                                               "structure": {"identifiant": {"nom": "acception", "type": "primaire"}}}],
                                  "parents": [{"nom": "groupe", "attribut": "sens"},
                                              {"nom": "entrée", "attribut": "sens"}]},
                    "sous-vedette": {"entités": [{"nom": "sous-entrée", "attributs": {"vedette": None},
                                                  "structure": {"identifiant": {"nom": "vedette", "type": "primaire"}}}],
                                     "parents": [{"nom": "sens", "attribut": "sous-entrées"},
                                                 {"nom": "entrée", "attribut": "sous-entrées"},
                                                 {"nom": "groupe", "attribut": "sous-entrées"}]},
                    "définition": {"entités": [{"nom": "définition", "attributs": {"définition": None},
                                                "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                   "parents": [{"nom": "sous-entrée", "attribut": "définitions"},
                                               {"nom": "sens", "attribut": "définitions"},
                                               {"nom": "groupe", "attribut": "définitions"},
                                               {"nom": "entrée", "attribut": "définitions"}]},
                    "étiquette sémantique": {"entités": [{"nom": "étiquette sémantique", "attributs": {"nom": None},
                                                          "structure": {}}],
                                             "parents": [{"nom": "définition", "attribut": "étiquettes sémantiques"}]},
                    "restriction": {"entités": [{"nom": "restriction", "attributs": {"restriction": None},
                                                "structure": {}}],
                                   "parents": [{"nom": "sous-entrée", "attribut": "restrictions"},
                                               {"nom": "sens", "attribut": "restrictions"},
                                               {"nom": "groupe", "attribut": "restrictions"},
                                               {"nom": "entrée", "attribut": "restrictions"}]},
                    "glose": {"entités": [{"nom": "glose", "attributs": {"glose": None},
                                           "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                              "parents": [{"nom": "sous-entrée", "attribut": "gloses"},
                                          {"nom": "sens", "attribut": "gloses"},
                                          {"nom": "groupe", "attribut": "gloses"},
                                          {"nom": "entrée", "attribut": "gloses"}]},
                    "équivalent": {"entités": [{"nom": "équivalent", "attributs": {"traduction": None}, "structure": {}}],
                                   "parents": [{"nom": "sous-entrée", "attribut": "équivalents"},
                                            {"nom": "sens", "attribut": "équivalents"},
                                            {"nom": "groupe", "attribut": "équivalents"},
                                            {"nom": "entrée", "attribut": "équivalents"}]},
                    "sens littéral": {"entités": [{"nom": "sens littéral", "attributs": {"sens littéral": None}, "structure": {}}],
                                   "parents": [{"nom": "définition", "attribut": "sens littéraux"}]},
                    "exemple": {"entités": [{"nom": "exemple", "attributs": {"exemple": None},
                                             "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                "parents": [{"nom": "sous-entrée", "attribut": "exemples"},
                                            {"nom": "sens", "attribut": "exemples"},
                                            {"nom": "groupe", "attribut": "exemples"},
                                            {"nom": "entrée", "attribut": "exemples"}]},
                    "traduction d'exemple": {"entités": [{"nom": "traduction d'exemple", "attributs": {"traduction": None},
                                                          "structure": {}}],
                                             "parents": [{"nom": "exemple", "attribut": "traductions"}]},
                    "commentaire d'exemple": {"entités": [{"nom": "commentaire d'exemple", "attributs": {"commentaire": None},
                                                          "structure": {}}],
                                             "parents": [{"nom": "traduction d'exemple", "attribut": "commentaires"}]},
                    "référence": {"entités": [{"nom": "entrée", "attributs": {"référence": None}, "structure": {}},
                                              {"nom": "sous-entrée", "attributs": {"référence": None}, "structure": {}},
                                              {"nom": "groupe", "attributs": {"référence": None}, "structure": {}},
                                              {"nom": "exemple", "attributs": {"référence": None}, "structure": {}}],
                                             "parents": None},
                    "nom scientifique": {"entités": [{"nom": "nom scientifique", "attributs": {"nom": None}, "structure": {}}],
                                         "parents": [{"nom": "sous-entrée", "attribut": "noms scientifiques"},
                                                     {"nom": "sens", "attribut": "noms scientifiques"},
                                                     {"nom": "groupe", "attribut": "noms scientifiques"},
                                                     {"nom": "entrée", "attribut": "noms scientifiques"}]},
                    "information encyclopédique": {"entités": [{"nom": "information encyclopédique", "attributs": {"information": None},
                                                                "structure": {}}],
                                                   "parents": [{"nom": "sous-entrée", "attribut": "informations encyclopédiques"},
                                                               {"nom": "sens", "attribut": "informations encyclopédiques"},
                                                               {"nom": "groupe", "attribut": "informations encyclopédiques"},
                                                               {"nom": "entrée", "attribut": "informations encyclopédiques"}]},
                    "note": {"entités": [{"nom": "note", "attributs": {"note": None}, "structure": {}}],
                             "parents": [{"nom": "définition", "attribut": "notes", "conditions": {"langue": "identique"}}]},
                    "domaine sémantique": {"entités": [{"nom": "domaine sémantique", "attributs": {"domaine": None}, "structure": {}}],
                                                          "parents": [{"nom": "sous-entrée", "attribut": "domaines sémantiques"},
                                         {"nom": "sens", "attribut": "domaines sémantiques"},
                                         {"nom": "groupe", "attribut": "domaines sémantiques"},
                                         {"nom": "entrée", "attribut": "domaines sémantiques"}]},
                    "relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"cible": None}, "structure": {}}],
                                            "parents": [{"nom": "entrée", "attribut": "relations sémantiques"},
                                                        {"nom": "sous-entrée", "attribut": "relations sémantiques"},
                                                        {"nom": "groupe", "attribut": "relations sémantiques"},
                                                        {"nom": "sens", "attribut": "relations sémantiques"}]},
                    "type de relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"type": None}, "structure": {}}],
                                                    "parents": [{"nom": "entrée", "attribut": "relations sémantiques"},
                                                                {"nom": "sous-entrée", "attribut": "relations sémantiques"},
                                                                {"nom": "groupe", "attribut": "relations sémantiques"},
                                                                {"nom": "sens", "attribut": "relations sémantiques"}]},
                    "cible de relation sémantique": {"entités": [{"nom": "relation sémantique", "attributs": {"cible": None}, "structure": {"factorisable": True}},
                                                                 {"entité": "type de relation sémantique", "attributs": {}, "copie": {"type": "type"}}],
                                                     "parents": None},
                    "traduction de relation sémantique": {"entités": [{"nom": "traduction de relation sémantique", "attributs": {"traduction": None}, "structure": {}}],
                                                          "parents": [{"nom": "relation sémantique", "attribut": "traductions de relation sémantique"}]},
                    "étymologie": {"entités": [{"nom": "étymologie", "attributs": {"étymon": None}, "structure": {}}],
                                   "parents": [{"nom": "entrée", "attribut": "étymologies"},
                                               {"nom": "sous-entrée", "attribut": "étymologies"}]},
                    "glose d'étymologie": {"entités": [{"nom": "glose d'étymologie", "attributs": {"glose": None}, "structure": {}}],
                                           "parents": [{"nom": "étymologie", "attribut": "gloses d'étymologie"}]},
                    "langue d'étymologie": {"entités": [{"nom": "étymologie", "attributs": {"langue": None}, "structure": {}}],
                                            "parents": None},
                    "tableau": {"entités": [{"nom": "tableau", "attributs": {"identifiant": None},
                                             "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                "parents": [{"nom": "sous-entrée", "attribut": "tableaux"},
                                            {"nom": "sens", "attribut": "tableaux"},
                                            {"nom": "entrée", "attribut": "tableaux"}]},
                    "encadré": {"entités": [{"nom": "encadré", "attributs": {"identifiant": None},
                                             "structure": {"identifiant": {"nom": None, "type": "primaire"}}}],
                                "parents": [{"nom": "sous-entrée", "attribut": "encadrés"},
                                            {"nom": "sens", "attribut": "encadrés"},
                                            {"nom": "entrée", "attribut": "encadrés"}]},
                    "titre": {"entités": [{"nom": "titre", "attributs": {"titre": None}, "structure": {}}],
                              "parents": [{"nom": "tableau", "attribut": "titres"},
                                          {"nom": "encadré", "attribut": "titres"}]},
                    "contenu": {"entités": [{"nom": "contenu", "attributs": {"contenu": None}, "structure": {}}],
                                "parents": [{"nom": "tableau", "attribut": "contenus"},
                                          {"nom": "encadré", "attribut": "contenus"}]},
                    "date": {"entités": [{"nom": "date", "attributs": {"date": None}, "structure": {}}],
                             "parents": [{"nom": "sous-entrée", "attribut": "dates"},
                                         {"nom": "entrée", "attribut": "dates"}]},
                    "source": {"entités": [{"nom": "entrée", "attributs": {"source": None}, "structure": {}}],
                               "parents": None},
                    "référence bibliographique": {"entités": [{"nom": "entrée", "attributs": {"référence bibliographique": None}, "structure": {}},
                                                              {"nom": "sous-entrée", "attributs": {"référence bibliographique": None}, "structure": {}}],
                               "parents": None},
                    "image": {"entités": [{"nom": "image", "attributs": {"chemin": None}, "structure": {}}],
                              "parents": [{"nom": "entrée", "attribut": "médias"}]},
                    "légende d'image": {"entités": [{"nom": "image", "attributs": {"légende": None}, "structure": {}}],
                              "parents": None},
                }
            },
            "LMF - Relation sémantique avec classe grammaticale": dict(self.formats_sortie["LMF"], **{
                "entités": dict(self.formats_sortie["LMF"]["entités"], **{
                    "classe grammaticale": {"entités": [{"nom": "entrée lexicale", "attributs": {"partie du discours": None}, "structure": {}},
                                                        {"nom": "sous-entrée lexicale", "attributs": {"partie du discours": None}, "structure": {}},
                                                        {"nom": "relation sémantique", "attributs": {"partie du discours": None}, "structure": {}}],
                                            "parents": None},
                })
            }),

        }
