configuration:
  chemin source: informations linguistiques.yml
base:
  chemin source: mwotlap.lex
  format d’entrée: MDF Alex
  format de sortie: LMF Alex
  identifiant: mwotlap
général:
  nom: Essai d’un dictionnaire
  auteur: Alexandre François
  commentaire: LMF-α
  ordre lexicographique:
      - [a, b, d, e, ē, g, h, i, k, l, m, m̄, n, [̄n, n̄], o, ō, p, q, r, s, t, u, v, w, y]
langues:
- code: mlv
  type de caractères: latin
  autoglossonyme: mwotlap
  glossonyme: mwotlap
  statut: source
- code: fra
  type de caractères: latin
  autoglossonyme: français
  glossonyme: français
  statut: cible
- code: eng
  type de caractères: latin
  autoglossonyme: English
  glossonyme: anglais
  statut: cible
- code: bis
  type de caractères: latin
  autoglossonyme: Bislama
  glossonyme: bichelamar
  statut: cible
xml:
  chemin cible: mwotlap.xml
  format: α #αβγ
  langue: fra
  XSL: style.xsl
  tri: normal

