configuration:
  chemin source: informations linguistiques.yml
base:
  chemin source: teanu.lex
  format d’entrée: MDF Alex
  format de sortie: LMF Alex
  identifiant: teanu
général:
  nom: Essai d’un dictionnaire
  auteur: Alexandre François
  commentaire: LMF-α
  ordre lexicographique:
  - [a, b, bw, d, e, g, i, j, k, l, m, mw, n, ng, [̄n, n̄], o, p, pw, r, s, t, u, v, w]
langues:
- code: tkw
  type de caractères: latin
  autoglossonyme: teanu
  glossonyme: teanu
  statut: source
- code: fra
  type de caractères: latin
  autoglossonyme: français
  glossonyme: français
  statut: cible
- code: eng
  type de caractères: latin
  autoglossonyme: English
  glossonyme: anglais
  statut: cible
- code: bis
  type de caractères: latin
  autoglossonyme: Bislama
  glossonyme: bichelamar
  statut: cible
xml:
  chemin cible: teanu.xml
  format: α #αβγ
  langue: fra
  XSL: style.xsl
  tri: normal

